name: CI Pipeline

# Trigger the workflow only when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up your programming language environment (example for Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies (you can customize this based on your project)
      - name: Install dependencies
        run: npm install

      # Run tests (or other tasks)
      - name: Run tests
        run: npm test

      # Build the application (customize this step for your project)
      - name: Build application
        run: npm run build
